Fix uncaught TypeError at createObjectStore :bug:
Fixes #15172
---
As shown here
Uncaught TypeError: Cannot read property 'createObjectStore' of undefined
```
At C:\Users\Midhu\AppData\Local\atom\app-1.18.0\resources\app\src\state-store.js:17

TypeError: Cannot read property 'createObjectStore' of undefined
    at IDBOpenDBRequest.dbOpenRequest.onupgradeneeded (~/AppData/Local/atom/app-1.18.0/resources/app/src/state-store.js:17:19)
```
I haven't been able to reproduce the error locally but I suspect this might be the cause.